const ADMIN_USER="admin",ADMIN_PASS="12345";
function login(){if(document.getElementById("adminUser").value===ADMIN_USER&&document.getElementById("adminPass").value===ADMIN_PASS){sessionStorage.kdAdmin="1";showPanel()}else document.getElementById("loginMsg").textContent="Wrong username or password."}
function logout(){sessionStorage.removeItem("kdAdmin");location.reload()}
function showPanel(){document.getElementById("loginBox").hidden=true;document.getElementById("panel").hidden=false;renderAll()}
document.addEventListener("DOMContentLoaded",()=>{if(sessionStorage.kdAdmin)showPanel()});
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function packages(){return JSON.parse(localStorage.getItem("kdPackages")||"null")||[{name:"Kashmir Tour",price:"Starting ₹12,999",desc:"Beautiful valleys, mountains and unforgettable experiences.",image:"https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80"},{name:"Goa Tour",price:"Starting ₹8,999",desc:"Beaches, sightseeing and exciting activities.",image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80"},{name:"Char Dham Yatra",price:"Custom Package",desc:"A memorable spiritual journey with complete travel support.",image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"}]}
function addPackage(){const p={name:pName.value.trim(),price:pPrice.value.trim(),desc:pDesc.value.trim(),image:pImage.value.trim()};if(!p.name)return alert("Package name required");const a=packages();a.push(p);localStorage.setItem("kdPackages",JSON.stringify(a));pName.value=pPrice.value=pImage.value=pDesc.value="";renderAll()}
function delPackage(i){const a=packages();a.splice(i,1);localStorage.setItem("kdPackages",JSON.stringify(a));renderAll()}
function renderPackages(){adminPackages.innerHTML=packages().map((p,i)=>`<div class="adminpackage"><img src="${esc(p.image)}"><div><b>${esc(p.name)}</b><br>${esc(p.price)}<br><button onclick="delPackage(${i})">Delete</button></div></div>`).join("")}
function bookings(){return JSON.parse(localStorage.getItem("kdBookings")||"[]")}
function saveBookings(a){localStorage.setItem("kdBookings",JSON.stringify(a))}
function renderBookings(){let a=bookings(),q=(search.value||"").toLowerCase();a=a.filter(x=>`${x.name} ${x.mobile} ${x.service}`.toLowerCase().includes(q));bookingsEl.innerHTML=a.length?a.map(x=>`<div class="adminrow"><b>${esc(x.name)}</b> • ${esc(x.mobile)}<br>${esc(x.service)} | ${esc(x.date)} | ${esc(x.from)} → ${esc(x.to)}<br>${esc(x.message)}<br><select onchange="status(${x.id},this.value)"><option ${x.status==="New"?"selected":""}>New</option><option ${x.status==="Confirmed"?"selected":""}>Confirmed</option><option ${x.status==="Completed"?"selected":""}>Completed</option><option ${x.status==="Cancelled"?"selected":""}>Cancelled</option></select><a class="btn small" href="https://wa.me/91${esc(x.mobile)}" target="_blank">WhatsApp</a><button onclick="delBooking(${x.id})">Delete</button></div>`).join(""):"No bookings found."}
function status(id,v){const a=bookings();const x=a.find(z=>z.id==id);if(x)x.status=v;saveBookings(a);renderAll()}
function delBooking(id){saveBookings(bookings().filter(x=>x.id!=id));renderAll()}
function renderAll(){renderPackages();renderBookings();const a=bookings();total.textContent=a.length;newCount.textContent=a.filter(x=>x.status==="New").length;confirmed.textContent=a.filter(x=>x.status==="Confirmed").length;completed.textContent=a.filter(x=>x.status==="Completed").length}
const bookingsEl=document.getElementById("bookings");