const WA="917222826299";
const defaultPackages=[
{name:"Kashmir Tour",price:"Starting ₹12,999",desc:"Beautiful valleys, mountains and unforgettable experiences.",image:"https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80"},
{name:"Goa Tour",price:"Starting ₹8,999",desc:"Beaches, sightseeing and exciting activities.",image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80"},
{name:"Char Dham Yatra",price:"Custom Package",desc:"A memorable spiritual journey with complete travel support.",image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"}];
function getPackages(){return JSON.parse(localStorage.getItem("kdPackages")||"null")||defaultPackages}
function renderPackages(){const el=document.getElementById("packageList");if(!el)return;el.innerHTML=getPackages().map(p=>`<article class="package"><img src="${esc(p.image)}"><div class="body"><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="price">${esc(p.price)}</div><a class="btn" href="#booking" onclick="document.getElementById('service').value='Tour Package';document.getElementById('message').value='Package: ${esc(p.name)}'">Enquire Now</a></div></article>`).join("")}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",()=>{renderPackages();const f=document.getElementById("bookingForm");if(f)f.addEventListener("submit",sendBooking)});
function sendBooking(e){e.preventDefault();const g=id=>document.getElementById(id).value.trim();const booking={id:Date.now(),name:g("name"),mobile:g("mobile"),service:g("service"),date:g("date"),from:g("from"),to:g("to"),passengers:g("passengers"),budget:g("budget"),message:g("message"),status:"New",created:new Date().toLocaleString("en-IN")};const list=JSON.parse(localStorage.getItem("kdBookings")||"[]");list.unshift(booking);localStorage.setItem("kdBookings",JSON.stringify(list));const text=`*KD GOLDEN TRAVELS - BOOKING ENQUIRY*%0A%0A👤 Name: ${booking.name}%0A📱 Mobile: ${booking.mobile}%0A✈️ Service: ${booking.service}%0A📅 Date: ${booking.date}%0A📍 From: ${booking.from}%0A🎯 To: ${booking.to}%0A👥 Passengers: ${booking.passengers}%0A💰 Budget: ${booking.budget}%0A📝 Requirement: ${booking.message}`;window.open(`https://wa.me/${WA}?text=${text}`,"_blank");e.target.reset();alert("Booking enquiry saved and WhatsApp opened.")}